export const LEAGUE_LIST_REQUEST = 'LEAGUE_LIST_REQUEST';
export const LEAGUE_LIST_SUCCESS = 'LEAGUE_LIST_SUCCESS';
export const LEAGUE_LIST_ERROR   = 'LEAGUE_LIST_ERROR';

export const LEAGUE_SHOW_REQUEST = 'LEAGUE_SHOW_REQUEST';
export const LEAGUE_SHOW_SUCCESS = 'LEAGUE_SHOW_SUCCESS';
export const LEAGUE_SHOW_ERROR   = 'LEAGUE_SHOW_ERROR';

export const TEAM_LIST_REQUEST = 'TEAM_LIST_REQUEST';
export const TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS';
export const TEAM_LIST_ERROR   = 'TEAM_LIST_ERROR';

export const TEAM_SHOW_REQUEST = 'TEAM_SHOW_REQUEST';
export const TEAM_SHOW_SUCCESS = 'TEAM_SHOW_SUCCESS';
export const TEAM_SHOW_ERROR   = 'TEAM_SHOW_ERROR';

export const MATCH_LIST_REQUEST = 'MATCH_LIST_REQUEST';
export const MATCH_LIST_SUCCESS = 'MATCH_LIST_SUCCESS';
export const MATCH_LIST_ERROR   = 'MATCH_LIST_ERROR';